foo_bar/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('menu/', include('menu.urls')),
    path('admin/', admin.site.urls),
]

menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.detail, name='form'),
    path('save/', views.save, name='save'),
    path('<int:item_id>/item_detail/', views.item_detail, name='item_detail'),
    path('<int:item_id>/edit_save/', views.edit_save, name='edit_save'),
    path('<int:item_id>/delete', views.delete, name='delete'),
    path('<int:item_id>/edit', views.edit, name='edit'),
]

menu/models.py
from django.db import models

class Item_hdr(models.Model):
    SNACK = 'S'
    DRINK = 'D'
    TYPE = (
        (SNACK, 'Snack'),
        (DRINK, 'Drink'),
    )
    item_name = models.CharField(max_length=200)
    item_type = models.CharField(max_length=1, choices=TYPE, default=DRINK)
    
    def __str__(self):
        return self.item_name

    @staticmethod
    def get_snacks():
        snack_list = Item_hdr.objects.filter(item_type='S').order_by('id')
        return snack_list

    @staticmethod
    def get_drinks():
        drink_list = Item_hdr.objects.filter(item_type='D').order_by('id')
        return drink_list


class Item_ingredients(models.Model):
    item = models.ForeignKey(Item_hdr, on_delete=models.CASCADE)
    ingredient = models.CharField(max_length=200)

    def __str__(self):
        return self.ingredient

class Related_items(models.Model):
    item = models.ForeignKey(Item_hdr, on_delete=models.CASCADE, related_name='item_hdr_key')
    related_item = models.ForeignKey(Item_hdr, on_delete=models.CASCADE, related_name='related_items')

    def __str__(self):
        return self.related_item.item_name

menu/forms.py
from django import forms

from .models import Item_hdr

class ItemForm(forms.ModelForm):
    class meta:
        model = Item_hdr
        fields = ('item_name','item_type','related_items')

menu/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
import pdb

from menu.models import Item_hdr


def index(request):
    template = loader.get_template('menu/index.html')
    context = {'snack_list' : Item_hdr.get_snacks(), 'drinks_list' : Item_hdr.get_drinks()}
    return HttpResponse(template.render(context, request))


def item_detail(request, item_id):
    item = Item_hdr.objects.get(id=item_id)
    template = loader.get_template('menu/item_detail.html')
    context = {'item': item}
    return HttpResponse(template.render(context, request))


def detail(request):
    item_list = Item_hdr.objects.all
    template = loader.get_template('menu/detail.html')
    context = {'item_list': item_list}
    return HttpResponse(template.render(context, request))


def save(request):
    #pdb.set_trace()
    item_name = request.POST['item_name']
    item_type = request.POST['type']
    ingredient = request.POST.getlist('ingredients[]')
    temp = Item_hdr(item_name=item_name, item_type=item_type)
    temp.save()
    for ing in reversed(ingredient):
        temp.item_ingredients_set.create(ingredient=ing)
    rel = temp.item_hdr_key
    related = request.POST.getlist('related')
    for rel_id in related:
        rel.create(related_item=(Item_hdr.objects.get(id=rel_id)))
    return HttpResponseRedirect(reverse('menu:index'))


def delete(request, item_id):
    i = Item_hdr.objects.get(id=item_id)
    i.delete()
    return HttpResponseRedirect(reverse('menu:index'))


def edit(request, item_id):
    item_list = Item_hdr.objects.all
    template = loader.get_template('menu/edit.html')
    edit_item = Item_hdr.objects.get(id=item_id)
    list=[]
    for ei in edit_item.item_hdr_key.all():
        list.append(ei.related_item.id)
    context = {'item_list': item_list, 'edit_item': edit_item, 'related_list': list}
    return HttpResponse(template.render(context, request))


def edit_save(request, item_id):
    edit_item = Item_hdr.objects.get(id=item_id)
    edit_item.item_name = request.POST['item_name']
    edit_item.item_type = request.POST['type']
    edit_item.save()
    edit_item.item_ingredients_set.all().delete()
    edit_item.item_hdr_key.all().delete()
    ingredient = request.POST.getlist('ingredients[]')
    related = request.POST.getlist('related')
    for ing in ingredient:
        edit_item.item_ingredients_set.create(ingredient=ing)
    for rel_id in related:
        edit_item.item_hdr_key.create(related_item=(Item_hdr.objects.get(id=rel_id)))
    return HttpResponseRedirect(reverse('menu:index'))

#c.create(related_item=(Item_hdr.objects.get(id=1)))

menu/templates/menu/base.html
{% load static %}
<html>
    <head>
        <title>foo_bar</title>
        <link href="{% static 'css/form.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        <header>
            <div class="row">
                <div class="col-sm-4">
                    <ul>
                        <li><a href="{% url 'menu:index' %}"><span id="home" class="glyphicon glyphicon-home"></span></a></li>
                    </ul>
                </div>
                <div class="col-sm-8">
                    <h1 style="margin-left: 100px">foo_bar</h1>
                </div>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="{% static "js/form.js" %}"></script>
    </body>
</html>

menu/templates/menu/detail.html
{% extends 'menu/base.html' %}

{% block content %}
    <div class="container">
<form name="new_form" action="{% url "menu:save" %}" method="post" onsubmit="return(validate());">
{% csrf_token %}
<br>
<label>Name: </label><br>
    <input type="text" name="item_name"><br><br>

    <label class="radio-inline"><input type="radio" name="type" id="S" value="S"><b>Snack</b></label>
    <label class="radio-inline"><input type="radio" name="type" id="D" value="D"><b>Drink</b></label><br><br>
<div id="ingredient-div">
<label>Ingredient: </label><br>
    <input type="text" name="ingredients[]"> <input type="button" class="butn" id="plus_btn" value="+"><input type="button" class="butn" id="minus_btn" value="-"><br>
</div>
    <label>Related Items: </label>
<div>
<select multiple="multiple" name="related" id="related_items">
    {% for item in item_list %}
        <option value={{ item.id }}>{{ item.item_name }}</option>
    {% endfor %}
</select>

</div><br>
<input type="submit" value="Submit" />
</form>
    </div>
{% endblock %}

menu/templates/menu/edit.html
{% extends 'menu/base.html' %}

{% block content %}
    <div class="container">
<form name="new_form" action="{% url "menu:edit_save" edit_item.id %}" method="post" onsubmit="return(validate());">
{% csrf_token %}
<br>
<label>Name: </label><br>
    <input type="text" name="item_name" value={{edit_item.item_name}}><br><br>

    <label class="radio-inline"><input type="radio" name="type" id="S" value="S" {% if edit_item.item_type == 'S' %}checked{% endif %}><b>Snack</b></label>
    <label class="radio-inline"><input type="radio" name="type" id="D" value="D" {% if edit_item.item_type == 'D' %}checked{% endif %}><b>Drink</b></label><br><br>
<div id="ingredient-div">
    <label>Ingredient: </label><br>
{% for ing in edit_item.item_ingredients_set.all %}
    <input type="text" name="ingredients[]" value="{{ ing.ingredient }}"> {% if forloop.counter == 1 %} <input type="button" class="butn" id="plus_btn" value="+"><input type="button" class="butn" id="minus_btn" value="-">{% endif %}<br>
{% endfor %}
</div>
    <label>Related Items:</label>
<div>
<select multiple="multiple" name="related" id="related_items">
    {% for item in item_list %}
        <option value={{ item.id }} {% if item.id in related_list %} selected {% endif %}>{{ item.item_name }}</option>
    {% endfor %}
</select>
</div><br>
<input type="submit" value="Submit" />
</form>
    </div>
{% endblock %}

menu/templates/menu/index.html
{% extends 'menu/base.html' %}

{% block content %}
<div class="container">
{% if snack_list %}
    <div class="row">
        <div class="col-sm-6">
            <h2>Snacks</h2>
        </div>
    <a href="{% url 'menu:form' %}"> <span style="margin-top: 30px" class="glyphicon glyphicon-plus"></span> </a>
    </div>
    <dl>
    {% for snack in snack_list %}
        <div class="row">
            <div class="col-sm-6"> <dt><a href="{% url 'menu:item_detail' snack.id%}"> <h4>{{snack.item_name}}</h4> </a></div>
            <a href="{% url 'menu:edit' snack.id %}"> <span class="glyphicon glyphicon-edit"></span> </a> |
            <a href="{% url 'menu:delete' snack.id %}"> <span class="glyphicon glyphicon-trash"></span> </a> </dt>
        </div>
    {% endfor %}
    </dl>
{% else %}
    <p>No Snacks available!<a href="{% url 'menu:form' %}"> <span style="margin-top: 30px" class="glyphicon glyphicon-plus"></span> </a></p>
{% endif %}


{% if drinks_list %}
<div class="row">
        <div class="col-sm-6">
            <h2>Drinks</h2>
        </div>
<a href="{% url 'menu:form' %}"> <span style="margin-top: 30px" class="glyphicon glyphicon-plus"></span> </a>
</div>
    <dl>
    {% for drink in drinks_list %}
        <div class="row">
            <div class="col-sm-6"> <dt><a href="{% url 'menu:item_detail' drink.id%}"> <h4>{{drink.item_name}}</h4> </a></div>
            <a href="{% url 'menu:edit' drink.id %}"> <span class="glyphicon glyphicon-edit"></span> </a> |
            <a href="{% url 'menu:delete' drink.id %}"> <span class="glyphicon glyphicon-trash"></span> </a> </dt>
        </div>

    {% endfor %}
    </dl>
{% else %}
    <p>No Drinks available!<a href="{% url 'menu:form' %}"> <span style="margin-top: 30px" class="glyphicon glyphicon-plus"></span> </a> </p>
{% endif %}
</div>
{% endblock %}

menu/templates/menu/item_detail.html
{% extends 'menu/base.html' %}

{% block content %}
    <div class="container">
    <h1>{{ item.item_name }}</h1>
    <dl><dt><h2><u>Ingredients</u></h2></dt>
        {% for ing in item.item_ingredients_set.all %}<dd><h4> - {{ing.ingredient}} </h4></dd>{% endfor %}
    </dl>
    <dl><dt><h2><u>Related Items</u></h2></dt>
        {% for rel_item in item.item_hdr_key.all %}<dd><h4> - <a href="{% url 'menu:item_detail' rel_item.related_item.id%}"> {{rel_item.related_item.item_name}} </a></h4></dd>{% endfor %}
    </dl>
    </div>
{% endblock %}